name: Build and Publish Image

on:
  pull_request:
    branches:
      - main
  push:
    branches: 
      - main
  release:
    types: ["published"]

jobs:
  build-and-publish:
    name: Build and Publish
    uses: sei-jbooz/Crucible-Github-Actions/.github/workflows/docker-build.yaml@docker-multi-arch-native
    with:
      imageName: cmusei/player-api
      additionalTarget: debug
      versionMode: csproj
      versionFiles: Player.Api/Player.Api.csproj
      push: "false"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
